name: Continuous delivery in GitHub

on:
  workflow_dispatch:  # 这将允许你在 GitHub UI 上手动触发工作流

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 使用较新的 v2 版本
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2  # 使用较新的 v2 版本
        with:
          java-version: 1.8
          distribution: 'adopt'  # 指定 JDK 分发源，AdoptOpenJDK

      - name: Build project using Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: ckb-sdk-java
          path: build/libs/*.jar  # 确保这个路径匹配你的 JAR 文件位置
