name: Continuous delivery in GitHub

on:
  workflow_dispatch:  # 这行将触发方式更改为手动触发

jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag manually
        run: echo "Manually triggered build."
        
      - name: Checkout branch
        uses: actions/checkout@v2  # 更新为最新的 v2 版本
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2  # 更新为最新的 v2 版本
        with:
          java-version: 1.8
          distribution: 'adopt'  # 指定JDK分发版本，adopt 是 AdoptOpenJDK

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2  # 使用 upload-artifact 动作上传构建文件
        with:
          name: ckb-sdk-java
          path: build/libs/*.jar  # 确保路径匹配你的 JAR 文件位置
