name: Continuous delivery in GitHub

on:
  workflow_dispatch:

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'adopt'

      - name: Build project using Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ckb-sdk-java
          path: build/libs/*.jar
